server:
  port: 8080
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    #public IP
    url: jdbc:postgresql://147.45.144.17:5432/prmo_db
    #private IP
    #url: jdbc:postgresql://192.168.0.4:5432/prmo_db
    username: admin
    password: "<mYZ2?RMyyug}l"
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        show_sql: true
        temp:
          use_jdbc_metadata_defaults: false
        cache:


  liquibase:
    change-log: classpath:liquibase/changelog.yaml
#  thymeleaf:
#    prefix: classpath:/templates/
#    cache: false